# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - alpha_controller

  alpha_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - peacetolero_alpha_axis_e
      - peacetolero_alpha_axis_d
      - peacetolero_alpha_axis_c
      - peacetolero_alpha_axis_b
      - peacetolero_alpha_axis_a