# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    alpha_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

alpha_controller:
  ros__parameters:
    joints:
      - peacetolero_alpha_axis_e
      - peacetolero_alpha_axis_d
      - peacetolero_alpha_axis_c
      - peacetolero_alpha_axis_b
      - peacetolero_alpha_axis_a
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity