/**:
  ros__parameters:
    robot_description_kinematics:
      peacetolero_alpha:
        kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.5
        kinematics_solver_attempts: 10