# Default initial positions for peacetolero_alpha_config's ros2_control fake system

initial_positions:
  peacetolero_alpha_axis_a: 0
  peacetolero_alpha_axis_b: 0
  peacetolero_alpha_axis_c: 0
  peacetolero_alpha_axis_d: 1.57
  peacetolero_alpha_axis_e: 0
